### ISSUE TITLE
day=[i*7//len(train_df) for i in range(len(train_df))]==>全0 list

### ISSUE THREAD

**Issue by TenYearMan** [guoday/ICME2019-CTR#1]
郭大，split_data()里面这行代码是不是有误？请问您是按照什么划分训练 验证集的呢？

**Comment by guoday** [comment]
> 郭大，split_data()里面这行代码是不是有误？请问您是按照什么划分训练 验证集的呢？

时间划分，不是全0，是0-6的list，分别代表第几天

**Comment by TenYearMan** [comment]
> > 郭大，split_data()里面这行代码是不是有误？请问您是按照什么划分训练 验证集的呢？
> 
> 时间划分，不是全0，是0-6的list，分别代表第几天

get it,谢谢郭大。
