### ISSUE TITLE
xdeepfm

### ISSUE THREAD

**Issue by chen849157649** [guoday/ICME2019-CTR#2]
你好，我是新手，看了下里面的模型，似乎不是xdeepFM，与xdeepFM相比speed与AUC的trade-off哪个更好，有做过比较吗？谢谢

**Comment by guoday** [comment]
你最好看一下这个repo的原论文https://ieeexplore.ieee.org/document/8795067。xdeepfm只用到了其中CIN来获取交互特征，除此之外还有Key-Value Memory提取浮点数，word2vec和deepwalk提取文本和图特征。因此来说AUC是要比xdeepfm高很多的，至于speed话肯定比xdeepFM要慢的。

**Comment by guoday** [comment]
> 你好，我是新手，看了下里面的模型，似乎不是xdeepFM，与xdeepFM相比speed与AUC的trade-off哪个更好，有做过比较吗？谢谢

你最好看一下这个repo的原论文https://ieeexplore.ieee.org/document/8795067
xdeepfm只用到了其中CIN来获取交互特征，除此之外还有Key-Value Memory提取浮点数，word2vec和deepwalk提取文本和图特征。因此来说AUC是要比xdeepfm高很多的，至于speed话肯定比xdeepFM要慢的。
